# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Traceme < Formula
  desc "Local activity logger: periodic screenshots → Vision LLM → JSONL"
  homepage "https://github.com/gtn1024/traceme"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/gtn1024/traceme/releases/download/v0.1.0/traceme_0.1.0_darwin_amd64.tar.gz"
    sha256 "8d64fa5757d143735d995683214ce0c21081377260cdd00ba936529fccb6dab5"

    define_method(:install) do
      bin.install "traceme"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/gtn1024/traceme/releases/download/v0.1.0/traceme_0.1.0_darwin_arm64.tar.gz"
    sha256 "cf632cedf6c2f916931e4eefd33e03bc2ea2c99acd3d118b57ea7d8cc09d42ba"

    define_method(:install) do
      bin.install "traceme"
    end
  end

  test do
    system "#{bin}/traceme", "version"
  end
end
