# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Traceme < Formula
  desc "Local activity logger: periodic screenshots → Vision LLM → JSONL"
  homepage "https://github.com/gtn1024/traceme"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/gtn1024/traceme/releases/download/v0.2.0/traceme_0.2.0_darwin_amd64.tar.gz"
    sha256 "eb0d6b95bbfc319264582fa96ffeba61c02a1f82dc7795858f102cbf213e7553"

    define_method(:install) do
      bin.install "traceme"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/gtn1024/traceme/releases/download/v0.2.0/traceme_0.2.0_darwin_arm64.tar.gz"
    sha256 "4ce09752ba249af7ade7f0913611512d5ef4624dc55490929efeead98f10ab64"

    define_method(:install) do
      bin.install "traceme"
    end
  end

  test do
    system "#{bin}/traceme", "version"
  end
end
